// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-n5WjA_OzfG-hpOm4XRciR3wqJRMYsQ',
    appId: '1:734368751985:web:4fe853d89f25244f1ad6d0',
    messagingSenderId: '734368751985',
    projectId: 'flutter-firebase-dev-605fb',
    authDomain: 'flutter-firebase-dev-605fb.firebaseapp.com',
    storageBucket: 'flutter-firebase-dev-605fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9OIupVg-odaJENZp9kunsCwMZXzxLqDY',
    appId: '1:734368751985:android:9f6a04060d07a8a51ad6d0',
    messagingSenderId: '734368751985',
    projectId: 'flutter-firebase-dev-605fb',
    storageBucket: 'flutter-firebase-dev-605fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCy5EPygt6A9MlwQW-LmSHYPkXc5s_ECA',
    appId: '1:734368751985:ios:6fe62835a112faea1ad6d0',
    messagingSenderId: '734368751985',
    projectId: 'flutter-firebase-dev-605fb',
    storageBucket: 'flutter-firebase-dev-605fb.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirebase',
  );
}
